language: python

python:
  - 3.6
  
sudo: required

services:
  - docker

before_install:
  - docker build . -t server

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" registry.heroku.com;
    docker push server;
    fi

install: true
